### ISSUE TITLE
Help! UnicodeDecodeError:

### ISSUE THREAD

**Issue by yangleics3333** [construct/construct#1032]
Hello, I have been trying to use the [oct-converter](https://github.com/marksgraham/OCT-Converter) project for data format conversion recently, using construct/core. py, but I encountered an issue with Unicode DecodeError,
My development environment is: Python 3.10
The error message is as follows:

<img width="918" alt="image" src="https://github.com/construct/construct/assets/30650469/d8f7b7ac-0a6c-4f2f-a4ec-66b8f7558a58">

I hope everyone can help me solve this problem. I am looking forward to its normal luck. Thank you all.

**Comment by shearer12345** [comment]
That looks to be a bug in oct-converter rather than construct, so best to report it over there.

I had a quick look at what oct-converter is doing and in https://github.com/marksgraham/OCT-Converter/blob/main/oct_converter/readers/binary_structs/e2e_binary.py for parsing "magic2" it is expecting ASCII values (`”magic2" / PaddedString(12, "ascii"),`), but getting a value outside that range. (0xe1 is 225 in decimal, which is outside the 0-127 range of valid ASCII).

It's possible "magic2" is in some other encoding, or is just a sequence of 12 bytes - it's unclear from the documentation at https://bitbucket.org/uocte/uocte/wiki/Heidelberg%20File%20Format as `char[12]` is ambiguous. It looks like a c-language definition where `char` is used both for bytes and characters.

Try reporting this to oct-converter and see how you get on.

**Comment by arekbulski** [comment]
There is (or was) a bug in String parsing classes where if you parsed a data that could not be encoded or decoded properly, the String class throws an exception that is not ConstructError-derived. This has implications, if you use the String class in a Select or something that depends on catching ConstructErrors. However, your issue does not seem to relate to this. Therefore I am going to close it.
