### ISSUE TITLE
What would you like to be added to Construct?

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#527]
Currently in the queue is enum.IntEnum support (#456 ), Pickled class (#508) , and a [compiler](https://construct.readthedocs.io/en/latest/compilation.html) for performance. But what would you like to add to it?

What was recently added, is on Transition page:
https://construct.readthedocs.io/en/latest/transition29.html

**Comment by yannayl** [comment]
Is there a description for each of the suggestions?

I don't really understand what 'compiler' means.

**Comment by arekbulski** [comment]
RTFM to the rescue, of course! :grin: But seriously, you will find helpful explanation on those.
https://construct.readthedocs.io/en/latest/compilation.html
https://construct.readthedocs.io/en/latest/transition29.html

**Comment by arekbulski** [comment]
Enum support was requested in #456 .

**Comment by yannayl** [comment]
Hmm, compiler is cool, but I don't really see the value in it. I mean, python is slow. Binary parsing in high-level interpreted languages are slow. So, while cool, it seems not too important optimization. Has anyone asked for it? Is there a benchmark or anything?
I mean, if I needed binary parser with tight speed requirements I would use Kaitai, but also, I wouldn't use python.

The IntEnum sounds like the better option. A user asked for. It's value is clear. And frankly, it's much easier to implement :)

**Comment by arekbulski** [comment]
I am pretty sure that Kaitai->Python is slower than Construct (compiled). Neither is gonna beat C stdio but thats not a reason not to have it. And no, nobody asked for it. Came out of goodness in my heart. :stuck_out_tongue: 
And note that there were much larger efforts (from Google) to speed up Python, so its not like speed doesnt matter. It just matters... less. There is a benchmark at bottom of docs page, its 2x speedup on a simple example.

**What would be useful to you, if not compilation?** I am asking for suggestions for new features.

**Comment by yannayl** [comment]
I see. I have this conservative approach saying that you should implement only the vitals because maintenance is a bitch.

I would love having TRUELY lazy parsing. Parsing that only reads the necessary bytes to parse so field. I think I even opened an issue back then, about LazyContainers not supporting true lazyness.

**Comment by yannayl** [comment]
#417 that's the one

**Comment by arekbulski** [comment]
Yeah, I remember that ticket. That red warning still hangs on docs site. I will add your request, but (unfortunately) is a "research" topic. Still +1 to it. I am aware that Kaitai doesnt support lazy parsing either, I am a co-maintainer there as well.

**Comment by yannayl** [comment]
Oh, how cool! Yeah, I have a model in my of how to build such a thing, I toyed with the idea of writing some Kaitai lazy interpreter, but never got to actually do it. I think functional language is the best approach as you can evaluate a function only when you need it's value and otherwise pass it as a parameter, so instead of returning a value you return a partially bound function and you only evaluate the function when you need that specific value. Don't know if I'm clear here, just head it circulating in my head.

Anyway, the practical scenario of this feature is parsing a binary structure over a slow network connection, so you only want the specific bytes needed for to get the value and that's it. It's very common in CTF when you have a controlled memory leak and you remotely parse the ELF to find the locations of specific symbols.

**Comment by arekbulski** [comment]
Just pointing out, you were complaining that compilation is not very useful (it cuts runtime by half) and yet you request lazy parsing (so it increases performance). Not that I mind. :blush: I find both features helpful, so thank you for your suggestions. I will take it over from here.

**Comment by yannayl** [comment]
In the CTF scenario, often you can't read specific addresses or specific values (like NULL), depending on the vulnerability you are exploiting. Requesting for unnecessary bytes can crash the whole exploit for something you don't really need. (Currently we do ugly hacks to get around it.)
So it's not an optimization.

And also, IO penalty is usually far worse than CPU/memory penalty, so I believe it's a far super optimization. But I don't have benchmarks.

**Comment by arekbulski** [comment]
You are making a good point. Could you look at the current implementation of LazyStruct and tell me what could possibly be done better there?
https://github.com/construct/construct/blob/master/construct/core.py#L4082

One improvement would be to detect which fields require which previous fields, like Bytes(this.count). But this is a heavy feature that would require changing infrastructure. 

What is exactly that you mean by "true laziness"? Thats not a common technical term.

**Comment by Metadorius** [comment]
I would like to be able to know the index of the struct in the array so that I can reference it inside of this struct, for example, something like this:
`voxel = Struct(
    "index" / Computed(this.IndexInArray()),
    #something something
)`

**Comment by arekbulski** [comment]
Could you open a new Issue and restate your request? Please.

**Comment by arekbulski** [comment]
@Metadorius 
Index class was added, and will be included in next release shortly.

**Comment by yannayl** [comment]
See #597
