### ISSUE TITLE
Embedding BitStruct

### ISSUE THREAD

**Issue by edobez** [construct/construct#680]
Hello,
is there a way to embed a BitStruct inside a Struct without nesting it?

In the documentation it's written that BitStruct are non-nestable, but I can still do this:
```
format = Struct(
   "a" / BitStruct(
      "b" / Bit,
      Padding(7)
   ),
   "c" / Int8ul
)
```
... but I can't do:
```
format = Struct(
   Embedded(BitStruct(
      "b" / Bit,
      Padding(7)
   )),
   "c" / Int8ul
)
```
because it throws me the error ``construct.core.ConstructError: Embedding only works with: Struct, Sequence, FocusedSeq, Union``.

Is my only way working with solely BitStructs when dealing with mixed types (bytes and bits)?
Thanks

**Comment by arekbulski** [comment]
If you are referring to [this chapter](https://construct.readthedocs.io/en/latest/bitwise.html#important-notes), then you are misrepresenting it. It implies that BitStruct is not nestable inside another BitStruct, because the inner one would operate on 1/64th of a byte, not 1/8th.

Under new embedding semantics, its simply not possible implementation-wise to embed an instance of Bitwise. However, its also not possible to embed an instance of Switch, yet there is a macro EmbeddedSwitch that works around that limitation. I might be able to devise something similar, but otherwise you just cant embed it, you need to nest it.

**Comment by edobez** [comment]
Ok, now I get what the documentation mean, thanks.

I could think of a workaround for not using the Embedded BitStruct, but I would like to ask you what is the best way to create a structure with mixed bytes and bits given the current implementation.
The data I need to parse/build is for a CAN-frame payload, which can house various types including floats which are not necessarily byte aligned.

**Comment by arekbulski** [comment]
Well, there is nothing wrong with using one huge BitStruct, that includes [Bytewise](https://construct.readthedocs.io/en/latest/api/bytes.html#construct.Bytewise)-wrapped fields. As far as I remember it, there is no requirement that it must be octet-aligned. Now that I am checking it, the chapter does not mention Bytewise class, its only listed in Core API pages. I will have it updated ASAP and notify you when its up.

**Comment by edobez** [comment]
Thanks for the suggestion. I ended up using one huge BitStruct as you said but with BitsIntegers. I will take a look to Bytewise as well.

**Comment by arekbulski** [comment]
I updated the docs:
https://construct.readthedocs.io/en/latest/bitwise.html#fields-that-work-with-bytes

**Comment by girtsf** [comment]
Just stumbled on this when looking for ways to embed a BitStruct. I poked around the source and see now why it isn't easy with the current implementation. But I just wanted to chime in with a vote that I would find it useful. :)
