### ISSUE TITLE
EmbeddedSwitch overwrites a field with None if it has the same name

### ISSUE THREAD

**Issue by boringhexi** [construct/construct#684]
```python
from construct import *

test_a = Struct(
    "data" / Int16ul,
    "data2" / Int16ul,
)

test_b = Struct(
    "data" / Float32l
)

test = EmbeddedSwitch(
    Struct(
        "type" / Enum(Int8ul, a=1,  b=2)
    ),
    this.type,
    {
        'a': test_a,
        'b': test_b,
    }
)

print(test.parse(b'\x01\0\0\x80\x3f'))
```

Result: The EmbeddedSwitch chooses `test_a` (as expected), but its `data` field gets overwritten with `None` as seen below.
```
Container: 
    type = (enum) a 1
    data = None
    data2 = 16256
```

**Comment by arekbulski** [comment]
The EmbeddedSwitch API docs shows you that the macro creates a Struct that contains all the fields, and Struct tutorial tells you that you should not be duplicating field names. It makes no official guarantees if you do, what happens in reality is that later field overrides the context entry. What you see is correct albeit not documented behavior of Struct class.

Construct is unable to solve this issue automatically for you. The field names are static, so the fourth field (testb data) is `'data' / If(this.type == 'b', 'data' / Float)`. The IF gets evaluated, and returns None correctly.  The Struct gets that value and inserts it into the context unconditionally and correctly. The obvious way to solve this is use different field names. Library cannot rename them for you. 

This reminds me of another issue that was kind of hot on the forum, about using Switch(Embedded). Note its the reverse usage of Embedded(Switch). The problem with that one was, the Embedded class would need to change flags dynamically (at parsing time) instead of being static. This would require rework of entire library infrastructure. What you ask would require making field names dynamic, which is just as hassle and as little benefit. 

Another solution would be to make Struct insert entries conditionally (if value is not None) but that would change the semantics in a way I dont like it.
