### ISSUE TITLE
Subconstruct should not inherit name

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#685]
This is for safety, the user might not be aware that some classes are wrappers and inherit the name of its subcon. Fields should only have explicit names, attached with / operator.

**Comment by arekbulski** [comment]
Fixed but Container search() seems to have been broken. @blapid If you would be willing to take a look at it and even fix it, I would be grateful. I dont understand how the search functionality works. 

The changes are in 0b7cfa08d96081769827bef7e93b97f2bffe7022 and test case in https://github.com/construct/construct/blob/master/tests/lib/test_search.py .

**Comment by blapid** [comment]
Long time since I looked at this, but I think it has something to do with `GreedyRange`.
`test_search_functionality` is the best example, the line that fails tries to find a key called 'ada' but it is not present because the GreedyRange is not getting parsed:
```
>>> obj1 = d.parse(b"\x11\x21\x22\x02\x02\x13\x51\x52")
>>> print obj1
Container: 
    aa = 17
    ab = Container: 
        aba = 33
        abb = 34
        abc = Container: 
            abca = 2
            abcb = Container: 
                abcb2a = 2
    ac = 19
```
The expected result is two more 'ad' structs with 'ada' fields, the 'ada' values should be 0x51 and 0x52.

It's entirely possible that the struct definition has changed and therefore it's not getting parsed as I intended back when I wrote this. Does it make sense?

**Comment by arekbulski** [comment]
It doesnt make sense... but I never understood the search feature in the first place. And its 2am in the middle of night. 

GreedyRange was recently updated but not in a way that would change parsing results in your code. Also I should point out, that your code is somewhat using / operator wrong. The subcon in GreedyRange is NOT supposed to be named. Only the instances that are directly members of a struct should have names. I will update the code asap accordingly. Maybe that will explain that part.

**Comment by arekbulski** [comment]
I fixed it. Sorry it was my silly mistake. The greedyrange field wasnt named (and I was too sleepy or just dumb not to notice it). Thank you for responding just the same. And for implementing it in the first place, obviously!
