### ISSUE TITLE
GreedyRange within Bytewise within BitStruct fails when parsing

### ISSUE THREAD

**Issue by tazle** [construct/construct#697]
I need to process some odd-length bitfields at the start of a structure which finishes with unspecified-length byte array. I thought I could just put a Bytewise(GreedyRange(Byte))
Test case
```
import array
from construct import *

def test_greedyrange():

    Test = "parent" / BitStruct(
        "a" / BitsInteger(3),
        "b" / BitsInteger(5),
        "rest" / Bytewise(GreedyRange(Byte))
    )

    data = array.array('B', [0x31, 1, 2, 3, 4, 5]).tostring()
    result = Test.parse(data)
    assert result.a == 1
    assert result.b == 17
    assert result.rest == [1,2,3,4,5]

```

Passing case that demonstrates that known-length array within Bytewise works as expected:
```
def test_array():

    Test = "parent" / BitStruct(
        "a" / BitsInteger(3),
        "b" / BitsInteger(5),
        "rest" / Bytewise(Array(5, Byte))
    )

    data = array.array('B', [0x31, 1, 2, 3, 4, 5]).tostring()
    result = Test.parse(data)
    assert result.a == 1
    assert result.b == 17
    assert result.rest == [1,2,3,4,5]
```

**Comment by arekbulski** [comment]
The undocumented truth is that BitStruct, when it was concieved a long time ago, was only meant to support simple stuff like BitsIntegers. Bytewise was added much later. This might give you an impression that you could insert whatever you like into this Bytewise/Bitwise sandwitch and its fine.

If you look at the documentation, [BitStruct](https://construct.readthedocs.io/en/latest/api/structs.html#construct.BitStruct) is actually Bitwise, and [Bitwise](https://construct.readthedocs.io/en/latest/api/core.html#construct.core.Bitwise) is usually Restreamed. So you look at [Restreamed](https://construct.readthedocs.io/en/latest/api/core.html#construct.core.Restreamed) and it tells you in eye-poking yellow that stream seeking is not possible inside. [GreedyRange](https://construct.readthedocs.io/en/latest/api/repeaters.html#construct.GreedyRange) does stream seeking, if you look at listed StreamError.
```py
d = BitStruct(
    "rest" / Bytewise(GreedyRange(Byte)),
)
d.parse(bytes(5))
```
You could use [GreedyBytes](https://construct.readthedocs.io/en/latest/api/bytes.html#construct.GreedyBytes) instead... but that fails due to completely unrelated problem. [RestreamBytesIO](https://github.com/construct/construct/blob/cc6ac452ca5a571e55950c4132600e2c1e8dfa50/construct/lib/bitstream.py#L18-L29) does not (currently) support reading till EOF. I could implement it, just need some time to get to it.
```py
d = BitStruct(
    "rest" / Bytewise(GreedyBytes),
)
d.parse(bytes(5))
```

**Comment by tazle** [comment]
I guess the workaround is to nest any bit-oriented fields so that the BitStruct doesn't have to embed any bytewise components. In the example it would be something like:

```
import array
from construct import *

def test_greedyrange():

    Test = "parent" / Struct(
        "header" / BitStruct(
            "a" / BitsInteger(3),
            "b" / BitsInteger(5)
        ),
        "rest" / GreedyRange(Byte)
    )

    data = array.array('B', [0x31, 1, 2, 3, 4, 5]).tostring()
    result = Test.parse(data)
    assert result.header.a == 1
    assert result.header.b == 17
    assert result.rest == [1,2,3,4,5]
```

**Comment by arekbulski** [comment]
Yes... this is how it was done before Bytewise was introduced. Its just that people nowadays like to embed stuff, nesting structs is so 2000-and-late... out of fashion. Good to know that this solves the problem for you. 

I will also investigate the other angle I mentioned, RestreamedBytesIO read till EOF.

**Comment by arekbulski** [comment]
I updated the docs to mention that GreedyRange does not work inside Bitwise:
https://construct.readthedocs.io/en/latest/basics.html#repeaters

**Comment by arekbulski** [comment]
I updated the Bitwise tutorial docs, full listing of classes that do not work inside Restreamed:
https://construct.readthedocs.io/en/latest/bitwise.html#fields-that-do-not-work-and-fail

RestreamedBytesIO was updated to read till EOF, so `Bytewise(GreedyBytes)` works now.
I am not yet done with `Bytewise(GreedyRange)`. Maybe that can be fixed as well, not sure.

**Comment by arekbulski** [comment]
Okie dokie, I think we can close the issue. Nesting a BitStruct works fine, Bytewise(GreedyBytes) works now after the update, and Bytewise(GreedyRange) cannot be supported I think.
