### ISSUE TITLE
Support Python 2 ASCII string literals in PaddedString

### ISSUE THREAD

**Issue by HL94DXU** [construct/construct#740]
I know that this is a known problem (as per the docs), but I haven't seen an issue for it.

The problem: I have Python 2.7/construct 2.8 code with which heavily utilizes constructs of the type which is now called PaddedString(<length>, 'ascii'), and I want to update the code to use construct 2.9.
Converting all the string literals in my code to unicode prior to sending them to the _build_ function would make me and a lot of other people sad.
(As a side note, it seems very odd that to built a PaddedString with an 'ascii' encoding you must pass a unicode string.)

Thus, I am looking for a workaround which would allow me passing ASCII string literals to the PaddedString's build function. (Without editing _construct_'s source code.)

One solution would be to inherit from StringEncoded and reimplement __encode_ such that it will not verify that the given string is unicode, but that would be a rather unpleasant solution.
If you have any other idea for a workaround, then I'd love to hear it.

Also, if there's an estimated time of fix for this problem?

Thank you.

**Comment by arekbulski** [comment]
Its not a bug and hence there will be no fix for it on library side. *String classes were designed to operate only on Unicode strings, with modern Python you are not supposed to be using bytes for text. Python 2 is no longer supported in any major way, not even by Python.org, its considered a relic of the past. I am sorry to tell you this, but if this was a commercial product, I would crack a sad joke that using Python 2 voids the warranty... I am not actively developing/supporting the library anymore, not much time I am willing to spend on Construct these days, and definitely not on supporting Python 2 issues which belongs to the archaeology department. 

I would recommend using a custom adapter, or a custom PaddedString class. If you name it the same as in the library, then it will be used instead of the one in library. Thats I think the easiest approach.

**Comment by HL94DXU** [comment]
I agree with your views regarding Python 2, but that's my reality.

> With modern Python you are not supposed to be using bytes for text.

I'm not sure I agree with that. b"strings" are still widely used in a lot of Python 3 code. (For example, if the string is designated to be sent over a telnet connection. There are also many other examples I've noticed.)

> *String classes were designed to operate only on Unicode strings.

Out of curiosity, will it break any functionality to change the line "if not isinstance(obj, unicodestringtype):" in the class StringEncoded such that it will also support byte strings?

If the answer is no, then I don't see a reason for not making this change.
(Apart from the fact that it's odd that you can't build ASCII PaddedStrings from ASCII strings, I think that ASCII strings (b"strings") are a useful feature even in Python 3, and supporting it would definitely not be an exercise in backwards-compatibility.)

**Comment by I4HJrl0** [comment]
I created a pull request which addresses this issue:
https://github.com/construct/construct/pull/746
- The pull request contains only a very small change (effectively, one word had to be changed).
- It doesn't break anything (according to Travis CI).
- IMHO supporting ASCII strings makes much sense even in Python 3 (in part, due to the reasons stated above).

**Comment by I4HJrl0** [comment]
@arekbulski could you please elaborate on why this issue was closed?

**Comment by arekbulski** [comment]
I already explained. String classes are for unicode and Bytes classes are for bytes. What you are suggesting goes against the intended design.

**Comment by I4HJrl0** [comment]
@arekbulski okay then. Are you perhaps familiar with a good alternative using Bytes classes?
I've tried several variations (e.g. using Padded) but haven't found something that serves as a good alternative to Construct 2.8 code such as `Const(b"Hello", String(10))` (note that the string length is longer than the default value).

**Comment by arekbulski** [comment]
Then use an archived version?

**Comment by I4HJrl0** [comment]
I wouldn't want to miss on 2.9's exciting features.

Do you mind if I open another issue (or reopen this one) with the question from the last comment (of how to use Bytes classes to achieve this behavior in Construct 2.9)?

**Comment by arekbulski** [comment]
Of course I would not mind. Issues are considered, at least by me because I seem to have much different approach to this than other projects, as a forum and not bug tracker. Open a ticket for any reason. There is a handful of other people that also post replies.
