### ISSUE TITLE
upgrading deprecated gallery to 2.9.x

### ISSUE THREAD

**Issue by chnd** [construct/construct#741]
Hi, I am quite new to Construct. I have a project that uses old version of Construct (2.5.1). The project is heavily using the protocol libraries in the deprecated gallery, including the protocol for ipv4. I am seeking advice if it is worth to update to the latest Construct (2.9.x) considering that I have to modify a large amount of codes? Also, is there a plan to upgrade the old collection of protocol libraries to 2.9.x?

**Comment by arekbulski** [comment]
The project is no longer actively developed, so unless you rewrite those IPSTACK protocols gallery samples yourself, no. If you would do that, I would gladly merge it into this repo. However please keep in mind that the gallery (not deprecated gallery) is supposed to be using the most recent and advanced classes, so its not a matter of just translating examples to / operator, its refactoring it.

I dont know if its worth it, but 2.5.x is not supported since like 1-2 years ago. If you ask for help with some 2.5 code, its likely I might not even look at it because classes have changed considerably since then and I am only interested in supporting the most recent version. You can still ask, of course.

**Comment by chnd** [comment]
Thanks for the suggestion. I will try to refactor the deprecated gallery.
