### ISSUE TITLE
Explicitly specifying length of a BitStruct?

### ISSUE THREAD

**Issue by fake-name** [construct/construct#742]
This might be a dumb question, but is there any way to have the BitStruct type validate the data length at build-time?

Basically, I'm writing a bunch of code that parses bitfields from embedded hardware. The documentation specifies a number of bits in a bitfield, and then the overall size of the bitfield. 

Right now, this means I have to manually count the bits in the BitStruct, and append the required padding to make it the correct size. 

Unsurprisingly, this is fiddly and extremely error-prone.

Is there a way I can say "This BitStruct must be *nnn* bits long, and error if it's not"? Or some other similar solution?

I could probably do this with a bunch of Tell/Compute construct entities, but I have a *lot* of these bitfields, and that would bloat up the number of entries in each construct parser for something that's basically only used once.

**Comment by arekbulski** [comment]
It has been quite a while since I worked on this library, I am not able to tell from memory but I would suggest looking at 2 things:
- Look at the Bitwise source, it uses either Transformed or Restreamed. Transformed has some checks for data length at parsing and building time. You might be able to use something like BitStruct(FixedSized(...)) or something else inside of it that is considered fixed size.
- Build a custom adapter or custom class. Advantage of adapters is that you can put imperative code in those despite the fact that Construct aims to be declarative in usage.
