### ISSUE TITLE
Long time to parse a binary file using parse_stream method.

### ISSUE THREAD

**Issue by olcoz8** [construct/construct#762]
The aim is to parse a binary file of 40 MB using the following code (Construct version 2.9.45, Python 3.6):

```
import construct as ctr

myFormat = ctr.Struct(
    "field_1" / ctr.Int16ul,
    "field_2" / ctr.Int16ul,
    "field_3" / ctr.Int16ul,
    "field_4" / ctr.Int16ul,
    "field_5" / ctr.Int16ul,
    "field_6" / ctr.Int16ul,
    "field_7" / ctr.Int16ul,
    "field_8" / ctr.Int16ul,
    "field_9" / ctr.Int16ul,
    "field_10" / ctr.Int16ul,
    "field_11" / ctr.Array(
        ctr.this.field_2,
        ctr.Array(
            ctr.this.field_1,
            ctr.Struct(
                "field_12" / ctr.Int16ul,
                "field_13" / ctr.Int16ul,
                "field_14" / ctr.Int16ul,
                "field_15" / ctr.Int32ul,
                "field_16" / ctr.Int32ul,
                "field_17" / ctr.Int32ul,
                "field_18" / ctr.Array(ctr.this._.field_3, ctr.Int16ul)
            )
        )
    )
)

myFormat = myFormat.compile()

with open(file_path, mode='rb') as f:
    parsedFile = myFormat.parse_stream(f)
```

Where _file_path_ is the path of the binary file to be parsed. 

The result is satisfactory; however, it takes a long time to do it (more than 20 seconds). 

Any insight would be grateful.

**Comment by arekbulski** [comment]
Use `from construct import *` and drop the whole prefix, it makes the code unreadable. Also you can use `parse_file` instead so that makes a little less code.But for performance: **pypy would be much faster than CPython, and it can be combined with compile() as well.** Otherwise I think its as fast as Python can do. Well, unless you only require a handful of the items, in which case you could attempt to use Lazy* classes. Be advised that those are not as throughly tested, and have issues with using context (this expressions) so lazy classes might simply not work. Its an experimental feature.

**Comment by olcoz8** [comment]
Thank you for the feedback. 

I already had in mind the option of using Lazy classes; however, as I need to use most of the items, this option doesn't seem to be suitable. And about using pypy, it is also not possible for me because that code is part of a project where everything else goes with CPython. Hence, if I cannot attempt any of those options, I imagine that I am reaching the fastest time with construct.

**Comment by arekbulski** [comment]
Yes, I think this is not only the fastest that Construct can do but the fastest that Python can do. The compile() method produces a very minimalistic code that I doubt could possibly be significantly improved upon. Pure python is slow for numerical computation (duh).

**Comment by olcoz8** [comment]
Thank you for the answers. I close the ticket.

**Comment by jruizaranguren** [comment]
@arekbulski , I do not agree it is the fastest that Python can do. Depends on your disk speed, but reading 40MB, and creating a bunch of primitives  and some numpy arrays takes no longer than half a second.

@olcoz8 is reporting 30 seconds. I guess it must be something related to how construct is parsing.

What's your opinion?

**Comment by arekbulski** [comment]
Well, since you are splitting the hair let me clarify: this is as fast Construct can do it. There are no obvious advise that I could give you, I am sorry. If you would like to explore alternative approaches: you could use a custom non-Construct parser using Cython. You could also check if prefetching entire file into memory makes it faster since (1) platter hard drives impose seek delays and (2) even SSDs would incur a context switch delay when invoking a syscall to read from a file, even if the data would come from buffer cache in RAM. That is, open the file, read entire content into a bytes, put that into BytesIO, then parse_stream. Do you understand what I am suggesting? If you would find that this makes a speedup, then please report it to us. I would be curious to know the measurements on this.
