### ISSUE TITLE
Advice: fixed length CString

### ISSUE THREAD

**Issue by marnunez** [construct/construct#763]
I have a field that has 30 chars reserved for a null terminated string, meaning:

- I have to read all 30 chars
- The string will end up in a \x00 before the 30 chars are over
- I might read gibberish after the \x00, that I have to ignore, so only do encoding and decoding before said \x00

Is there any construct that could help me with this use case? Which one should I adapt?

**Comment by arekbulski** [comment]
`CString` class does that, although I assume that you meant 30 bytes since there is no way to read "30 unicode characters" in current implementation. You might also want `FixedSized` or `Padded` to skip the remaining ~30 bytes so you can read the next field. And to build a blob too. Have you looked at the docs site?

**Comment by marnunez** [comment]
I have... and as I was reading your answer my palm was speeding towards my face.


```python
from construct import FixedSized, CString


def myString(length, encoding='utf-8'):
    return FixedSized(length, CString(encoding))

s = myString(10)
print (s.build("Hello"))
>> b'Hello\x00\x00\x00\x00\x00'
print (s.parse(b"Hello\x00\x12\x43\x12\x32"))
>> Hello

```
Something like this, right?

I was thinking on far-fetched stuff. Never actually stumbled with FixedSized before. Well, nevermind...

**Comment by arekbulski** [comment]
No problem.
