### ISSUE TITLE
Tunnel and Embed (version <=2.52)

### ISSUE THREAD

**Issue by VPaulV** [construct/construct#789]
Hi Guys,

I am trying to port pdbpase (https://github.com/moyix/pdbparse) to the new construct version but got a few issues that I cannot find how to solve. Could you please show me what is the analog in construct 2.9 for the following:
https://github.com/moyix/pdbparse/blob/dbbd55def11e4bd8820e79bac6f43efb479661d8/pdbparse/gdata.py#L30
And the Embed:
https://github.com/moyix/pdbparse/blob/dbbd55def11e4bd8820e79bac6f43efb479661d8/pdbparse/gdata.py#L9

I found Adapters and Tunnel transforms, but cannot get how I can apply them in the same way as it was done in 2.5.2

Thank you!

**Comment by arekbulski** [comment]
I am not supporing anything that uses Embedding. Period.

**Comment by VPaulV** [comment]
Good, could you check the Tunnel thing? Is there any way to re-implement it using the new construct? Some tips would be useful, kind sir ;)

**Comment by VPaulV** [comment]
Is it just conversion of binary data into PascalString, and on the next step this string is parsed from the start again?

**Comment by arekbulski** [comment]
This is so advanced class and I havent worked on this library for years now. Unless someone else monitors this forum and has the know-how to tell, no luck here.

**Comment by ikelos** [comment]
Hiya @VPaulV, I've found a way around the Embedding for the project you mentioned (I flatten the hierarchy by constructing new containers once they've been parsed).  Since the project typically doesn't reconstruct data into a PDB, that should be ok.  Please give it a try (pull request 46 on pdbparse) and let me know on there if there's any problems...  5:)

And yeah, the PascalString should probably just by Bytes, it seems to be used as a way of specifying a number of bytes based on a length taken from another field, so I've converted them to RestreamData which reads the data of the first item and then tries to fill it with the second (which is Greedy), but I don't think the PascalString was doing any actual conversion or anything clever.

Hope this helps!  5:)
