### ISSUE TITLE
Parsing newline-terminated text followed by bytes

### ISSUE THREAD

**Issue by DrPyser** [construct/construct#791]
Hi!

How does one parse something like an http message, which has a text header followed by arbitrary bytes? The text part is not length prefixed or null terminated, but ends with a newline.

Alternatively, how can I tell GreedyString to stop at newline characters?

Thanks!

**Comment by arekbulski** [comment]
GreedyString doesnt stop at anything, thats why its called "greedy". You need a CString class with some custom parameters.

**Comment by DrPyser** [comment]
I don't think I'm dealing with null-terminated strings, though. Does HTTP use a null-terminated string for its header?

**Comment by DrPyser** [comment]
I'm using HTTP as an example. I'm actually trying to implement a parser for [plumb message from plan 9's plumber](http://doc.cat-v.org/plan_9/4th_edition/papers/plumb).

**Comment by jpsnyder** [comment]
Unfortunately, we can no longer use CString because the terminator parameter has been removed with the 2.9 version.

However, despite it's name, with NullTerminated you can specify to terminate on something other than a null character using the "term" parameter, but you will need to use GreedyString as it's subconstruct due to the way it works.


```python
NewLineString = NullTerminated(GreedyString('utf8'), term=b'\n')

print(NewLineString.parse(b'this is a test\n'))
# u'this is a test'
```

**Comment by DrPyser** [comment]
Perfect, that's what I was looking for. Thanks!
