### ISSUE TITLE
Compiled builders analogous to compiled parsers

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#910]
I am looking at how compiled parsers work and the overall test shows something like: compiled parser takes 75% of time of a non-compiled parser. I think its time finally to implement compiled builders. What do you think guys? Have you used compiled instances yet? 

@yannayl @timrid 

The benchmarks:
![Zrzut ekranu z 2021-03-24 12-55-57](https://user-images.githubusercontent.com/5385838/112308477-788c8e00-8ca2-11eb-916b-ada3e078c5e8.png)

**Comment by arekbulski** [comment]
Done and ready for publish.

**Comment by yannayl** [comment]
I have never used them. I don't use python for anything that requires performance

**Comment by arekbulski** [comment]
I do. And I have seen people on this forum doing so as well. 

BTW set myself a goal to learn Golang this year. Can you recommend some good books on the topic, or a course?

**Comment by yannayl** [comment]
I'm not a go programmer so I have nothing to share from my experience :/
But there are many cool projects in go, specifically I am a fan of Docker and Syzkaller (as a user). Having well written projects as a reference usually helps me to understand the idioms of a new language.

**Comment by arekbulski** [comment]
So what language do you use for high performance?

**Comment by yannayl** [comment]
I was playing with Rust but it's infinite amount of pain in the beginning, so you have to be really determined. I used it to analyze large collection of data. Otherwise I use good old C (and sometimes C++).

But maybe I'm not a good example. I am doing mostly research so most of my production code is low level C that glues things together or break them apart. And some Javascript because I have to.
