### ISSUE TITLE
dataclass adapter

### ISSUE THREAD

**Issue by timrid** [construct/construct#932]
Hi again,

We have already talked here #886 about the support of type hints etc. that you do not want to include. But what do you think about an adapter for the standard python `dataclass` (comparable to the adapter for `namedtuple` which this library already supports).

I already have a similar implementation in my [construct-typing](https://github.com/timrid/construct-typing) repository, but I think it would be better to put it directly in this repository. My implementation would have to be modified a bit and the documentation would have to be extended. I would do the work and create a PR for this, but only if you don't say up front that you wouldn't accept such a PR.

This is an example of the usage of the current implemented class in my repository:
```python
import dataclasses
import construct as cs
import construct_typed as cst
import typing as t

@dataclasses.dataclass
class Image(cst.TContainerMixin):
    signature: t.Optional[bytes] = cst.sfield(cs.Const(b"BMP"))
    width: int = cst.sfield(cs.Int8ub)
    height: int = cst.sfield(cs.Int8ub)
    pixels: t.List[int] = cst.sfield(cs.Array(cs.this.width * cs.this.height, cs.Byte))

format = cst.TStruct(Image)
obj = Image(width=3, height=2, pixels=[7, 8, 9, 11, 12, 13])
print(format.build(obj))
print(format.parse(b"BMP\x03\x02\x07\x08\t\x0b\x0c\r"))
```

**Comment by arekbulski** [comment]
Sorry for the delay.  I seen your post 10 minutes ago but it took me a little time to come to a reply. Basically as you said, I am against adding static typing to the library. The first reason is this: I dont even understand what you wrote. Which means if we add this then I will need to add you as a maintainer because I cant take responsibility for this code. Secondly: I see no obvious benefits. I firmly believe that Python achieves correctness through readability, and achieves readability through lack of static typing. If we add this then we pay a lot in terms of readability and for no gain?

**Comment by arekbulski** [comment]
Btw the namedtuple adapter is shit and nobody uses it.

**Comment by timrid** [comment]
All right. I think it would bring advantages even if the readability suffers. Why else is the typing module extended in every new Python version? 
But I accept your opinion and then it's good that I asked before I created a PR. Then the idea with the dataclasses will only live in my repository for now.

PS: I think 10 min response time is quite good ;) So fast I manage it only rarely...
