### ISSUE TITLE
[question] ImportError: cannot import name 'BFloat32' from 'construct'

### ISSUE THREAD

**Issue by Naozumi520** [construct/construct#936]
Is it have no longer supported on the version now? If yes can anyone tell me which version should work for it? Thanks. :D

**Comment by arekbulski** [comment]
The type you describe BFloat32 does not exist since about 2016 so you must have been living on another planet for at least that long. Which would be obvious to you if you only bothered to read main documentation. Sorry but I wont entertain you. I hate stupid questions and broken English, and this is both. 

https://construct.readthedocs.io/en/latest/

**Comment by Naozumi520** [comment]
Thanks for your reply. ;)
