### ISSUE TITLE
How to achieve variable-length integers?

### ISSUE THREAD

**Issue by laf0rge** [construct/construct#962]
I'm working with various different binary formats, some of them using a variety of TLV encoding schemes.  

I've built my own TLV parser classes, and integrated construct to parse (and encode)  the 'value' part of the TLV.  Code can be found at
https://git.osmocom.org/pysim/tree/pySim/tlv.py

This generally works fine, and for most situations I could get away with what construct provides, plus a few adapters (https://git.osmocom.org/pysim/tree/pySim/construct.py)

Occasionally I'm encountering situations where the value part of a TLV contains variable-length integers.  I have not yet found any way to handle those in construct.  There is BytesInteger, but it requires the user to declare the number of bytes.

I would like to achieve the following behavior:
- decoding: use all the bytes provided by the input steram, interpret them as one n-bytes-long integer
- encoding: deetrmine the number of octets required to encode the provided integer, and generate the output bytes for that

I've thought it should be possible to do this with using the context somehow, but at least all my attmepts fail.

Is this supported in construct? If so, could anyone help?  If it is not supported, I guess I'd have to write my own Construct, despite the manual strongly discouraging that?

Thanks for this great tool!

**Comment by laf0rge** [comment]
"delay" of some minutes, are you kidding? Thanks for your ultra-fast feedback.

My implementation can be found in https://gerrit.osmocom.org/c/pysim/+/27169

It doesn't support encoding of signed integers, and it doesn't do any of the "compiled" stuff which I never used.

If you think  it deserves to be included upstream, I can submit a PR.

**Comment by arekbulski** [comment]
Believe it or not but I used to keep myself to a (rather high) standard of replying within 5 minutes. But now the library is not under active development, in fact it has not been for years, so I did let that go.

- GreedyInteger parsing: it looks exactly as I imagined it to be.
- "bytes rqd" is a fucking obscurism. Nobody except the both of us will not have a faintest fucking clue what it is supposed to mean. If its "bytes required" then write just that. 
- bytes required implementation: You can implement it in a loop instead of cases, especially that Python ints can be much longer than 64 bits. 
- Since you use the two functions, bytes2integer and integer2bytes, it means you opted to use the 2s complements. Refer to this wiki page and work it out. 
https://en.wikipedia.org/wiki/Integer_(computer_science)
- integertypes is a relic of the past. When Python 2 was still supported, this list had both "int" and "long". Now this is just the int.
- Compilation implementation is not required. By default, your class inherits a code that just defers the compiled code to use the code you wrote. You do not need to write it.
- I will think of importing it upstream. I am on the fence actually. Will need to think about it.

**Comment by laf0rge** [comment]
>     * GreedyInteger parsing: it looks exactly as I imagined it to be.

good.

>     * "bytes rqd" is a fucking obscurism. Nobody except the both of us will not have a faintest fucking clue what it is supposed to mean. If its "bytes required" then write just that.

It is a matter of the context in which one works.  I work in a telecom context where lots of acronyms are engrained in your brain.  IND==indication, RQD==required, REQ==request, etc.

>     * bytes required implementation: You can implement it in a loop instead of cases, especially that Python ints can be much longer than 64 bits.

done.
 
>     * integertypes is a relic of the past. When Python 2 was still supported, this list had both "int" and "long". Now this is just the int.

I just aligned with the existing construct codebase, to ensure consistency within the project.

Updated version now also has some minimal unit test coverage, see https://gerrit.osmocom.org/c/pysim/+/27169

Thanks again for your help.

**Comment by arekbulski** [comment]
Do you need help with the signed integers?

**Comment by laf0rge** [comment]
I have no need for signed, so for my use case I won't implement them, thanks. The unit tests I have are also sufficient for my needs, so I won't invest more time unless you'd want to merge it upstream.

**Comment by arekbulski** [comment]
Well then, I am glad that Construct works for you. :)

**Comment by arekbulski** [comment]
I found a bug. In `__bytes_required`, you should check if the obj is a negative number, not just self.signed. If the number is negative then the `i >> 8` will not converge to zero.
```py
>>> (-2**32)
-4294967296
>>> _>>8
-16777216
>>> _>>8
-65536
>>> _>>8
-256
>>> _>>8
-1
>>> _>>8
-1
>>> _>>8
-1
```
