### ISSUE TITLE
suppressing key in output dict for Optional?

### ISSUE THREAD

**Issue by laf0rge** [construct/construct#964]
Is there a way to suppress generationg "foo: None" in the output dictionary?

```
>>> oi =  Struct('foo'/Byte, 'record_len'/Optional(Int16ub))
>>> oi.parse(b'\x21')
Container(foo=33, record_len=None)
```
basically dropping the entire 'record_len' key/value pair if the optional part of the message didn't exist.

I tried the naive approach of moving the label inside the Optional, but that fails (as no label means don't show in dict):
```
>>> oi =  Struct('foo'/Byte, Optional('record_len'/Int16ub))
>>> oi.parse(b'\x21\x01\x00')
Container(foo=33)
```

**Comment by arekbulski** [comment]
Well, the only way I know of is to not name the subcon in a Struct, which means the parsing result will never be included in the dict. If you name the subcon, it will always be included even if it is a None. The Struct does not exhibit a "insert if" behavior.

You can reimplement the Struct class, or implement an Adapter that copies keys selectively:
```py
oi = SelectiveAdapter(Struct(..., ...))
```
Naming the subcon of Optional is pointless, because Subconstructs rarely if ever use the subcon name. If you are curious, just look into implementation of Optional. There is no "sc.name" in it right?

Sorry, I feel like you expected some easy switch or something. In this case, there isnt one.
